{
 "title": "GoToSocial Metrics",
 "description": "GoToSocial runtime metrics (filter by instance)",
 "tags": [
  "go",
  "golang",
  "gotosocial"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(go_goroutines, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(go_goroutines{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "GoToSocial Worker Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker Counts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{\"gotosocial.workers.client_api.count\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.delivery.count\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.dereference.count\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.fedi_api.count\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.processing.count\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.webpush.count\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Worker Queues",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{\"gotosocial.workers.client_api.queue\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.delivery.queue\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.dereference.queue\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.fedi_api.queue\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.processing.queue\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "{\"gotosocial.workers.webpush.queue\", job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "GoToSocial HTTP Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Request rate (total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate({\"http.server.requests_total\", job=\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate (client API)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (\"http.route\", \"http.status_code\") (rate({\"http.server.requests_total\", instance=~\"$instance\", job=\"$job\", 'http.route'=~\"/api.+\"}[$__rate_interval]))",
     "legendFormat": "{{http.route}} {{http.status_code}}"
    }
   ]
  },
  {
   "title": "Request rate (federation endpoints)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (\"http.route\", \"http.status_code\") (rate({\"http.server.requests_total\", instance=~\"$instance\", job=\"$job\", 'http.route'=~\"/(.well-known|users).+\"}[$__rate_interval]))",
     "legendFormat": "{{http.route}} {{http.status_code}}"
    }
   ]
  },
  {
   "title": "Request rate (fileserver)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (\"http.route\", \"http.status_code\") (rate({\"http.server.requests_total\", instance=~\"$instance\", job=\"$job\", 'http.route'=~\"/fileserver.+\"}[$__rate_interval]))",
     "legendFormat": "{{http.route}} {{http.status_code}}"
    }
   ]
  },
  {
   "title": "Request latency p95",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate({\"http.server.duration_milliseconds_bucket\", job=\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency  p99",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate({\"http.server.duration_milliseconds_bucket\", job=\"$job\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_mspan_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_buck_hash_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_gc_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"} - go_memstats_other_sys_bytes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{instance}}}"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"} - go_memstats_frees_total{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Rates of Allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  }
 ]
}